on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

permissions: read-all

jobs:
  tests:
    name: tests
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        ocaml: ["5.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set-up OCaml ${{ matrix.ocaml }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml }}
      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
